# Generated by Django 5.2.4 on 2025-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0003_department_employee_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table2',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
