# Generated by Django 5.2.4 on 2025-08-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0004_table1_table2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_dup',
            fields=[
            ],
            options={
                'ordering': ['-empno'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('DBApp.employee',),
        ),
    ]
