# Generated by Django 5.2.4 on 2025-08-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBApp', '0005_employee_dup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee_dup',
            options={'ordering': ['empno']},
        ),
        migrations.AddField(
            model_name='employee',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
